FROM python:3.9.16 as builder

# Set the working directory to /app
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./* /app
ENTRYPOINT [ "/bin/sh", "/app/scripts/startup.sh"]